package com.byit.fraud.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2018-01-31T16:10:25.098+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://archserver.wsdl.dataflux.com", name = "DataManagementServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DataManagementServicePortType {

    @WebMethod(operationName = "datasvc_ccapp__rt__match.ddf_in", action = "ccapp_rt_match.ddf*1*5A0E5D26ED700CE0")
    @RequestWrapper(localName = "datasvc_ccapp__rt__match.ddf_in", targetNamespace = "archserver.xsd.dataflux.com", className = "com.dataflux.xsd.archserver.Request")
    @ResponseWrapper(localName = "datasvc_ccapp__rt__match.ddf_out", targetNamespace = "archserver.xsd.dataflux.com", className = "com.dataflux.xsd.archserver.Response")
    public void datasvcCcappRtMatchDdfIn(
		    @WebParam(name = "table_", targetNamespace = "")
				    TableIn table,
		    @WebParam(mode = WebParam.Mode.OUT, name = "table_", targetNamespace = "")
				    javax.xml.ws.Holder<TableOut> table1
    );
}
