package com.byit.fraud.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Data Management Server
 *
 * This class was generated by Apache CXF 3.0.2
 * 2018-01-31T16:10:25.127+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "DMService", 
                  wsdlLocation = "http://fna:21036/datasvc/ccapp_rt_match.ddf?wsdl",
                  targetNamespace = "http://archserver.wsdl.dataflux.com") 
public class DMService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://archserver.wsdl.dataflux.com", "DMService");
    public final static QName DMService = new QName("http://archserver.wsdl.dataflux.com", "DMService");
    static {
        URL url = null;
        try {
            url = new URL("http://fna:21036/datasvc/ccapp_rt_match.ddf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DMService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://fna:21036/datasvc/ccapp_rt_match.ddf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DMService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DMService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DMService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DMService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns DataManagementServicePortType
     */
    @WebEndpoint(name = "DMService")
    public DataManagementServicePortType getDMService() {
        return super.getPort(DMService, DataManagementServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataManagementServicePortType
     */
    @WebEndpoint(name = "DMService")
    public DataManagementServicePortType getDMService(WebServiceFeature... features) {
        return super.getPort(DMService, DataManagementServicePortType.class, features);
    }

}
